networks:
- type: bridge
  config:
    ipv4.address: 192.0.2.1/24
    ipv4.nat: true
    ipv6.address: 2001:db8:f:1::1/64
    ipv6.nat: true
    ipv6.dhcp: false
    raw.dnsmasq: ra-param=lxdbr0,120
  description: "Default network"
  name: lxdbr0
storage_pools:
- config:
    size: 15GB
  description: ""
  name: default
  driver: btrfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
