networks:
- type: bridge
  config:
    ipv4.address: 192.0.2.1/24
    ipv4.nat: true
    ipv6.address: 2001:db8:f:1::1/64
    ipv6.nat: true
    ipv6.dhcp: false
    raw.dnsmasq: ra-param=lxdbr0,120
    bridge.hwaddr: "00:16:3e:ee:00:01"
  description: "Default network"
  name: lxdbr0
- config:
    ipv4.address: none
    ipv6.address: none
  name: r2customerA
- config:
    ipv4.address: none
    ipv6.address: none
  name: r3customerB
- config:
    ipv4.address: none
    ipv6.address: none
  name: r2r3
- config:
    ipv4.address: none
    ipv6.address: none
  name: r2r1
- config:
    ipv4.address: none
    ipv6.address: none
  name: r3r1
- config:
    ipv4.address: none
    ipv6.address: none
  name: r1peer200
- config:
    ipv4.address: none
    ipv6.address: none
  name: r1transit
- config:
    ipv4.address: none
    ipv6.address: none
  name: ixp
storage_pools:
- config:
    size: 15GB
  description: ""
  name: default
  driver: btrfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
