interface to_IXP
 description "IXP LAN Connection"
 ipv6 address 2001:db8:30:30::b/64
exit
!
interface lo
 ipv6 address 2001:db8:bbbb::b/128
exit
!
interface eth0
 description "Default network, do not use"
 shutdown
exit
!
ipv6 route 2001:db8:bbbb::/48 Null0
ipv6 route 2001:db8:bbbb:1::/64 Null0
ipv6 route 2001:db8:bbbb:2::/64 Null0
!
router bgp 300
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 neighbor 2001:db8:30:30::8 remote-as 30
 neighbor 2001:db8:30:30::8 description RS1
 no neighbor 2001:db8:30:30::8 enforce-first-as
 neighbor 2001:db8:30:30::9 remote-as 30
 neighbor 2001:db8:30:30::9 description RS2
 no neighbor 2001:db8:30:30::9 enforce-first-as
 !
 address-family ipv6 unicast
  network 2001:db8:30:30::/64
  network 2001:db8:bbbb::/48
  network 2001:db8:bbbb:1::/64
  network 2001:db8:bbbb:2::/64
  neighbor 2001:db8:30:30::8 activate
  neighbor 2001:db8:30:30::8 default-originate
  neighbor 2001:db8:30:30::8 prefix-list ANY in
  neighbor 2001:db8:30:30::8 prefix-list ANY out
  neighbor 2001:db8:30:30::9 activate
  neighbor 2001:db8:30:30::9 default-originate
  neighbor 2001:db8:30:30::9 prefix-list ANY in
  neighbor 2001:db8:30:30::9 prefix-list ANY out
 exit-address-family
exit
!
ipv6 prefix-list ANY seq 10 permit any
!
end
